routes/web.php
<?php
use App\Park;
use Illuminate\Support\Facades\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => ['auth']], function () {
    Route::resource('parks', 'ParkController');
    Route::resource('account', 'AccountController');
    Route::resource('dash', 'SensorController');
    Route::resource('equipments', 'EquipmentController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController');
});
    
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get ( '/search', 'SensorController@index')->name('search');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'type'
    ];
    
    public function equipment() {
        return $this->hasMany('App\Equipment');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use Log;

class CategoryController extends Controller
{
   /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();

        return view('Category.indexCategory', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = Category::all();
        return view('Category.addCategory', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'type' => 'required|string|max:255',
        ]);

        $category = new Category([
            'type' => $request->get('type'),
        ]);
        $category->save();
        return redirect('/categories')->with('Category Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        return view('Category.editCategory', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'type' => 'required|string|max:255',
        ]);

        $category = Category::find($id);
        $category->type = $request->get('type');
        $category->save();
        return redirect('/categories')->with('success', 'The category has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        return redirect('/categories')->with('success', 'Category deleted!');
    }
}

resources/views/Category/addCategory.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Categories</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    <form method="post" action="{{ route('categories.store') }}">
                @csrf
                <div class="form-group">
                    <label for="type">Type:</label>
                    <input type="text" class="form-control" name="type" />
                </div>

                <button type="submit" class="btn btn-secondary">Add Category</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/Category/editCategory.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Categories</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif

    <form method="post" action="{{ route('categories.update', $category->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">

                <label for="type">Category Name:</label>
                <input type="text" class="form-control" name="type" value="{{ $category->type }}">
            </div>

            <button type="submit" href="" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/Category/indexCategory.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Categories</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    @if(Auth::user()->organisation != null|| Auth::user()->level_of_access == 1)
  <table class="table table-striped">
        <thead>
            <tr><td>Type</td></tr>
        </thead>
        <div>
        <a style="margin: 19px;" href="{{ route('categories.create')}}" class="btn btn-primary">New Category</a>
        </div>  

        <tbody>
        @foreach($categories as $category)
            <tr>
                <td>{{$category->type}}</td>
                <td><a href="{{route('categories.edit', $category->id)}}" class="btn btn-primary">Edit</a> </td>
                <td><form action="{{ route('categories.destroy', $category->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button></form></td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @else
    <h1>Please select an organisation</h1>
    @endif

    @if(session()->get('success'))
        <div class="alert alert-success">
        {{ session()->get('success') }}  
        </div>
    @endif
</div>
</div>
@endsection