routes/web.php
<?php
use App\Park;
use Illuminate\Support\Facades\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => ['auth']], function () {
    Route::resource('parks', 'ParkController');
    Route::resource('account', 'AccountController');
    Route::resource('dash', 'SensorController');
    Route::resource('equipments', 'EquipmentController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController');
});
    
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get ( '/search', 'SensorController@index')->name('search');

app/Organisation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Organisation extends Model
{
    protected $fillable = [
        'name', 'type'
    ];

    public function user() {
        return $this->hasMany('App\User');
    }

}

app/Http/Controllers/OrganisationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Organisation;
use Log;

class OrganisationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $organisations = Organisation::all();
        return view('Organisation.indexOrganisation', compact('organisations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $organisation = Organisation::all();
        return view('Organisation.addOrganisation', compact('organisation'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'type' => 'required|string|max:255',
        ]);

        $organisation = new Organisation([
            'name' => $request->get('name'),
            'type' => $request->get('type'),
        ]);

        $organisation->save();
        return redirect('/organisations')->with('Park added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $organisation = Organisation::find($id);
        return view('Organisation.editOrganisation', compact('organisation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'type' => 'required|string|max:255',
        ]);

        $organisation = Organisation::find($id);
        $organisation->name = $request->get('name');
        $organisation->type = $request->get('type');
        $organisation->save();
        return redirect('/organisations')->with('updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $organisation = Organisation::find($id);
        $organisation->delete();

        return redirect('/organisations')->with('organisation deleted!');
    }
}

resources/views/Organisation/addOrganisation.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Organisation</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    @if(Auth::user()->level_of_access != 0)
    <form method="post" action="{{ route('organisations.store') }}">
        @csrf
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" name="name" />
        </div>

        <div class="form-group">
            <label for="type">Type:</label>
            <input type="text" class="form-control" name="type" />
        </div>

        <button type="submit" class="btn btn-secondary">Add Organisation</button>
    </form>
    @endif
   </div>
 </div>
</div>
@endsection

resources/views/Organisation/editOrganisation.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Organisation</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    @if(Auth::user()->level_of_access != 0)
    <form method="post" action="{{ route('organisations.update', $organisation->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" name="name" value="{{ $organisation->name }}">
            </div>
            <div class="form-group">
                <label for="type">Type:</label>
                <input type="text" class="form-control" name="type" value="{{ $organisation->type }}">
            </div>
            <button type="submit" href="" class="btn btn-primary">Update</button>
        </form>
        @endif
    </div>
</div>
@endsection

resources/views/Organisation/indexOrganisation.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Organisations</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    @if(Auth::user()->level_of_access != 0)
    <table class="table table-striped">
    <thead>
      <tr>
          <td>Name</td>
          <td>Type</td>
      </tr>
    </thead>
    <div>
        <a style="margin: 19px;" href="{{ route('organisations.create')}}" class="btn btn-primary">New Organisation</a>
    </div> 
    <tbody>
      @foreach($organisations as $organisation)
        <tr>
          <td>{{$organisation->name}} </td>
          <td>{{$organisation->type}} </td>
          <td><a href="{{route('organisations.edit', $organisation->id)}}" class="btn btn-primary">Edit</a></td>
          <td><form action="{{ route('organisations.destroy', $organisation->id)}}" method="post">
          @csrf
          @method('DELETE')
          <button class="btn btn-danger" type="submit">Delete</button></form></td>
        </tr>
      @endforeach
   </tbody>
</table>
@else
    <h1> You do not have permissions to access this page </h1>
    @endif
    @if(session()->get('success'))
        <div class="alert alert-success">
        {{ session()->get('success') }}  
        </div>
    @endif
 </div>
</div>
@endsection