routes/web.php
<?php
use App\Park;
use Illuminate\Support\Facades\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => ['auth']], function () {
    Route::resource('parks', 'ParkController');
    Route::resource('account', 'AccountController');
    Route::resource('dash', 'SensorController');
    Route::resource('equipments', 'EquipmentController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController');
});
    
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get ( '/search', 'SensorController@index')->name('search');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'address', 'address_two', 'contact_num', 'contact_two', 'level_of_access', 'organisation_id'
    ];
    
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function park() {
        return $this->hasMany('App\Park');
    }

    public function organisation() {
        return $this->belongsTo('App\Organisation');
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Organisation;
use Log;
use Hash;


class UserController extends Controller
{
   /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() 
    {
        $users = User::all();
        foreach($users as $user) {
            $data = $user->organisation; 
            Log::info($data);
        }
        return view('User.userIndex', compact('users', 'data'));
    }
 
 public function create()
    {
        $users = User::all();
        $organisations = Organisation::all();

        return View('User.addUser', compact('users', 'organisations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|max:255',
            'password' => 'required|string|min:8',
            'address' => 'required|string|min:10',
            'address_two' => 'nullable|string',
            'contact_num' => 'required|numeric|min:11',
            'conatct_two' => 'nullable|string',
        ]);

        $user = User::firstOrNew([
            'email' => $request['email'],
        ]);
        
        Log::info('Check' . $request->organisation_id);
        if($request->get('organisation_id') == 2) {
            $acessLevel = 1;
        } else {
            $acessLevel = 0;
        }
        $user->fill([
            'name' => $request->name,
            'password' => Hash::make($request->password),
            'address' => $request->address,
            'address_two' => $request->address_two,
            'contact_num' => $request->contact_num,
            'contact_two' => $request->contact_two,
            'organisation_id' => $request->organisation_id,
            'level_of_access' => $acessLevel,
            ]);
            
        $user->save();
        return redirect('/users')->with('User added');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $organisations = Organisation::all();
        $user = User::find($id);
        return view('User.editUser', compact('organisations', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|max:255',
            'password' => 'required|string|min:8',
            'address' => 'required|string|min:10',
            'address_two' => 'nullable|string',
            'conatct_num' => 'required|numeric|min:11',
            'conatct_two' => 'nullable|string|min:11',
        ]);

        if($request->get('organisation_id') == 2) {
            $acessLevel = 1;
        } else {
            $acessLevel = 0;
        }

        $user = User::find($id);
        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->address = $request->get('address');
        $user->address_two = $request->get('address_two');
        $user->contact_num = $request->get('contact_num');
        $user->contact_two = $request->get('contact_two');
        $user->organisation_id = $request->get('organisation_id');
        $user->level_of_access = $acessLevel;

        $user->save();
        return redirect('/users')->with('updated user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $suer = User::find($id);
        $suer->delete();

        return redirect('/users')->with('User deleted!');
    }
}

resources/views/User/addUser.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add User</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    @if(Auth::user()->level_of_access != 0)
    <form method="post" action="{{ route('users.store') }}">
                @csrf
                <div class="form-group">
                    <label for="name">name:</label>
                    <input type="text" class="form-control" name="name" />
                </div>
                <div class="form-group">
                    <label for="email">email:</label>
                    <input type="text" class="form-control" name="email" />
                </div>
                <div class="form-group">
                    <label for="password">password:</label>
                    <input type="password" class="form-control" name="password" />
                </div>
                <div class="form-group">
                    <label for="address">address:</label>
                    <input type="text" class="form-control" name="address" />
                </div>
                <div class="form-group">
                    <label for="address_two">address 2:</label>
                    <input type="text" class="form-control" name="address_two" />
                </div>
                <div class="form-group">
                    <label for="contact_num">contact num:</label>
                    <input type="text" class="form-control" name="contact_num" />
                </div>
                <div class="form-group">
                    <label for="contact_two">contact two:</label>
                    <input type="text" class="form-control" name="contact_two" />
                </div>
                <button type="submit" class="btn btn-secondary">Add User</button>
            </form>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/User/editUser.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit User</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    @if(Auth::user()->level_of_access != 0)
    <form method="post" action="{{ route('users.update', $user->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="name">name:</label>
                <input type="text" class="form-control" name="name" value="{{ $user->name }}">
            </div>
            <div class="form-group">
                <label for="email">email:</label>
                <input type="text" class="form-control" name="email" value="{{ $user->email }}">
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control" name="password" value="{{ $user->password }}">
            </div>
            <div class="form-group">
                <label for="address">address:</label>
                <input type="text" class="form-control" name="address" value="{{ $user->address }}">
            </div>
            <div class="form-group">
                <label for="address_two">address_two :</label>
                <input type="text" class="form-control" name="address_two" value="{{ $user->address_two }}">
            </div>
            <div class="form-group">
                <label for="contact_num">contact_num :</label>
                <input type="text" class="form-control" name="contact_num" value="{{ $user->contact_num }}">
            </div>
            <div class="form-group">
                <label for="contact_two">contact_two:</label>
                <input type="text" class="form-control" name="contact_two" value="{{ $user->contact_two }}">
            </div>
            <div class="form-group">
                <label for="organisation_id">Organisation Name:</label>
                <select name ="organisation_id">
                    @foreach ($organisations as $organisation)
                        <option value="{{$organisation->id}}">{{$organisation->name}}</option> 
                    @endforeach 
                </select>
            </div>
            <button type="submit" href="" class="btn btn-primary">Update</button>
        </form>
        @endif
    </div>
</div>
@endsection

resources/views/User/userIndex.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Users</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    @if(Auth::user()->level_of_access != 0)
    <table class="table table-striped">
    <thead>
        <tr>
            <td>Name</td>
            <td>Email</td>
            <td>Address</td>
            <td>Address 2</td>
            <td>Contact Number</td>
            <td>Contact 2</td>
            <td>Level of Access</td>
            <td>Organisation</td>
        </tr>
    </thead>
    
    <div>
        <a style="margin: 19px;" href="{{ route('users.create')}}" class="btn btn-primary">New User</a>
    </div> 
    <tbody>
        @foreach($users as $user)
        <tr>
            <td>{{$user->name}} </td>
            <td>{{$user->email}} </td>
            <td>{{$user->address}} </td>
            <td>{{$user->address_two}} </td>
            <td>{{$user->contact_num}} </td>
            <td>{{$user->contact_two}} </td>
            <td>{{$user->level_of_access}} </td>
            @if($user->organisation != null)
            <td>{{$user->organisation->name}} </td>
            @else 
            <td>No Organisation</td>
            @endif
            <td><a href="{{route('users.edit', $user->id)}}" class="btn btn-primary">Edit</a></td>
            <td><form action="{{ route('users.destroy', $user->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger" type="submit">Delete</button></form></td>
        </tr>
        @endforeach
    </tbody>
    </table>
    @else
    <h1> You do not have permissions to access this page </h1>
    @endif
    @if(session()->get('success'))
        <div class="alert alert-success">
        {{ session()->get('success') }}  
        </div>
    @endif
</div>
</div>
@endsection