routes/web.php
<?php
use App\Park;
use Illuminate\Support\Facades\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => ['auth']], function () {
    Route::resource('parks', 'ParkController');
    Route::resource('account', 'AccountController');
    Route::resource('dash', 'SensorController');
    Route::resource('equipments', 'EquipmentController');
    Route::resource('organisations', 'OrganisationController');
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController');
});
    
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::get ( '/search', 'SensorController@index')->name('search');

app/Park.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Park extends Model
{
    protected $fillable = [
        'location', 'user_id', 'name',
    ];

    public function user() {
        return $this->belongsTo('App\User');
    }

    protected function equipment() {
        return $this->hasmany('App\Equipment');
    }
}

app/Http/Controllers/ParkController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Park;
use Log;
use App\User;
use App\Equipment;
use App\Sensor;


class ParkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $park = Park::all();
        return view('Park.indexPark', compact('park'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $park = Park::all();
        $users = User::where('level_of_access', 0)->get();
        return view('Park.addPark', compact('park', 'users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $park = new Park([
            'name' => $request->get('name'),
            'location' => $request->get('location'),
        ]);
        Log::info('New Park Check : ' . $park);
        $user = User::find($request->get('user_id'));
        $park->user()->associate($user);
        $park->save();
        return redirect('/parks')->with('Park added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::where('level_of_access', 0)->get();
        $park = Park::find($id);
        return view('Park.editPark', compact('park', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Log::info('Park ID Check : ' . $id);
        Log::info('User ID Check : ' . $request->get('user_id'));
        $park = Park::find($id);
        $park->location = $request->get('location');
        $park->name = $request->get('name');
        $park->user_id = $request->get('user_id');
        Log::info('User ID check Park assign' .$park->user_id);
        $park->save();
        return redirect('/parks')->with('updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $park = Park::find($id);
        $park->delete();

        return redirect('/parks')->with('Park deleted!');
    }
}

resources/views/Park/addPark.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Parks</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    @if(Auth::user()->organisation != null|| Auth::user()->level_of_access == 1)
    <form method="post" action="{{ route('parks.store') }}">
        @csrf
        <div class="form-group">
            <label for="location">Location:</label>
            <input type="text" class="form-control" name="location" />
        </div>

        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" class="form-control" name="name" />
        </div>

        <div class="form-group">
          <label for="user_id">Park Manager:</label>
          <select name ="user_id">
          @foreach ($users as $user)
            <option value="{{$user->id}}">{{$user->name}}</option> 
          @endforeach 
          </select></div>
        <button type="submit" href="{{ route('parks.store', ['user_id'=>$user->id]) }}" class="btn btn-secondary">Add Park</button>
    </form>
    @else
    <h1>Please Select an organisation </h1>
    @endif
   </div>
 </div>
</div>
@endsection

resources/views/Park/editPark.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Edit Parks</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    @if(Auth::user()->organisation != null|| Auth::user()->level_of_access == 1)
    <form method="post" action="{{ route('parks.update', $park->id)}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="park">Park Name:</label>
                <input type="text" class="form-control" name="name" value="{{ $park->name }}">
            </div>
            <div class="form-group">
                <label for="location">Location:</label>
                <input type="text" class="form-control" name="location" value="{{ $park->location }}">
            </div>
            <div class="form-group">
                <label for="user_id">Park Manager</label>
                <select name="user_id">
                    @foreach($users as $user)
                        <option value="{{$user->id}}">{{$user->name}}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" href="" class="btn btn-primary">Update</button>
        </form>
        @else
        <h1>Please Select an organisation </h1>
        @endif
    </div>
</div>
@endsection

resources/views/Park/indexPark.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Parks</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    @if(Auth::user()->organisation != null|| Auth::user()->level_of_access == 1)
    <table class="table table-striped">
    <thead>
        <tr>
            <td>Location</td>
            <td>Park Name</td>
            <td>Park Manager</td>
        </tr>
    </thead>
    <div>
        <a style="margin: 19px;" href="{{ route('parks.create')}}" class="btn btn-primary">New park</a>
    </div> 
    <tbody>
      
        @foreach($park as $park)
        <tr>
            <td>{{$park->location}} </td>
            <td>{{$park->name}} </td>
            <td>{{$park->user->name}} </td>
            <td><a href="{{route('parks.edit', $park->id)}}" class="btn btn-primary">Edit</a></td>
            <td><form action="{{ route('parks.destroy', $park->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger" type="submit">Delete</button></form></td>
        </tr>
        @endforeach
    
    </tbody>
    </table>
    @else
    <h1>Please select an organisation</h1>
    @endif


    @if(session()->get('success'))
        <div class="alert alert-success">
        {{ session()->get('success') }}  
        </div>
    @endif
</div>
</div>
@endsection